name: HotPotTest
on: [push]
jobs:
  Explore-GitHub-Actions:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v3
     - name: Set up JDK 8
       uses: actions/setup-java@v1
       with:
           java-version: 8
     - name: Test with Java_main
       run: cd ${{ github.workspace }}/hw7/hotpotsystem && ./TestHotPot.java
